---
- name: Install Gitlab Runner (Debian)
  include: install-debian.yml
  when: ansible_os_family == 'Debian'

- name: Set global options.
  include: global-setup.yml

- name: Register Gitlab Runner.
  include: register-runner.yml
  when: gitlab_runner_registration_token != ''
