---
- hosts: dbservers
  roles:
    - common
    - docker

- hosts: appservers
  roles:
    - common
    - docker

- hosts: proxies
  roles:
    - common
    - docker

- hosts: gitlab-runners
  vars_files:
    - vars/main.yml
  roles:
    - gitlab-runner
